<yml_catalog>
    <shop>
        ...
        <offers>
            <offer id=DK0A4YJBD241S_32>
                <price>5900</price>
                <oldprice>6600</oldprice>
                <min_price>4425</min_price>
                <outlets>
                    <outlet instock="28" warehouse_name="склад 1"></outlet>
                    <outlet instock="13" warehouse_name="склад 2"></outlet>
                </outlets>
            </offer>
            ...
        </offers>
    </shop>
</yml_catalog>
